config/routes.rb
Rails.application.routes.draw do
  root to: "cars#landing"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cars
  # get 'user_session', to: 'users/sessions#show'
  resources :users, only: [:show]
  resources :transactions, only: [:index, :show, :create, :destroy] do
    resources :reviews
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :owned_cars, class_name: "Car", inverse_of: :owner

  # These are transactions as customer
  has_many :transactions, foreign_key: :user_id

  has_many :scheduled_transactions, -> { where(status: 'scheduled') }, class_name: 'Transaction', foreign_key: :user_id
  has_many :in_progress_transactions, -> { where(status: 'in progress') }, class_name: 'Transaction', foreign_key: :user_id
  has_many :completed_transactions, -> { where(status: 'completed') }, class_name: 'Transaction', foreign_key: :user_id

  # These are owned car transactions
  has_many :owned_transactions, through: :owned_cars, source: :transactions
  has_many :scheduled_cars, -> { where(transactions: { status: 'scheduled' }) }, through: :owned_cars, source: :transactions
  has_many :in_progress_cars, -> { where(transactions: { status: 'in progress' }) }, through: :owned_cars, source: :transactions
  has_many :completed_cars, -> { where(transactions: { status: 'completed' }) }, through: :owned_cars, source: :transactions

  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%# Banner and title for the page %>
<div class="w-full h-80 bg-center bg-no-repeat bg-cover bg-[url('https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80')]">
  <div class="w-full h-full bg-black bg-opacity-25">
    <div class="flex h-full justify-center items-center ">
      <%# Wanted to add text shadow to title but not supported by Tailwind.  Maybe maunally enter it? %>
      <h1 class="text-4xl text-white font-serif text-sky-100">User's Profile Page</h1>
    </div>
  </div>
</div>

<%# Div for current cars hosted by User %>
<div class="my-8 px-8">
  <p class="text-3xl text-center font-serif text-slate-800">Current Cars</p>
  <%# Div to hold current car cards %>
  <div class="grid grid-cols-3 grid-flow-row gap-3">
    <% @user.owned_cars.each do |car| %>
      <div>
        <%= link_to car_path(car) do %>
          <div class="max-w-sm rounded shadow-lg mt-6 shadow-xl bg-white w-80 mr-4 ml-4">
            <% if car.photos.count > 0%>
              <img class="w-full h-40 rounded-t"  alt="car picture" src="<%= cl_image_path car.photos[0].key, height: 300, width: 400, crop: :fill %>">
            <% else %>
              <img class="w-full h-40 rounded-t"  alt="car picture" src="./lamborghini.jpeg">
            <% end %>
            <div class="flex px-3	py-4 justify-between">
              <div class="font-semibold text-lg w-3/4	"><%= car.model %></div>
                <div class="flex items-center">
                    <p class="ml-2 text-sm font-bold text-gray-900">⭐️ <%= car.rating %></p>
                </div>
            </div>

            <div class="flex justify-center items-center">
              <span class="inline-block bg-blue-200 rounded-none px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">$<%= car.price %>/day</span>
              <span class="inline-block bg-blue-200 rounded-none px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= car.location %></span>
              <%= link_to edit_car_path(car) do %><p class="bg-teal-200 px-2 py-1 hover:bg-blue-200 rounded font-serif text-slate-800 mr-2">Edit<p><% end %>
              <%= link_to car_path(car), data: {turbo_method: :delete, turbo_confirm: "Are you sure?  This action cannot be undone."} do %><p class="bg-red-400 px-2 py-1 hover:bg-teal-200 rounded font-serif text-slate-800">Delete<p><% end %>
             </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= link_to new_car_path do%>
    <%# Div for add new car button %>
      <div class="mt-6 flex justify-center items-center h-full">
        <p class="bg-blue-200 px-2 py-1 hover:bg-teal-200 rounded font-serif text-slate-800">Add New Car</p>
      </div>
    <% end %>
  </div>
</div>