config/routes.rb
Rails.application.routes.draw do
  root to: "cars#landing"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cars
  # get 'user_session', to: 'users/sessions#show'
  resources :users, only: [:show]
  resources :transactions, only: [:index, :show, :create, :destroy] do
    resources :reviews
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :destroy]

  def index
    @transactions = policy_scope(Transaction)
    @owned_transactions = current_user.owned_transactions


    if params[:status].present?
      if params[:status] == "scheduled"
        @transactions = current_user.scheduled_transactions
        @owned_transactions = current_user.scheduled_cars
      elsif params[:status] == "in-progress"
        @transactions = current_user.in_progress_transactions
        @owned_transactions = current_user.in_progress_cars
      elsif params[:status] == "completed"
        @transactions = current_user.completed_transactions
        @owned_transactions = current_user.completed_cars
      end
    end

    if params[:role].present?
      @owned_transactions = [] if params[:role] == "user"
      @transactions = [] if params[:role] == "owner"
    end


    authorize @transactions if @transactions.count > 0
  end

  def show
    authorize @transaction
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user
    # Figure out later what the parameter naming is in the POST body
    @transaction.car = Car.find(params[:id])
    @transaction.status = "scheduled"
    authorize @transaction
    if @transaction.save
      redirect_to transaction_path(@transaction)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @transaction
    @transaction.destroy
    redirect_to transactions_path, { turbo_method: :delete, turbo_confirm: "Are you sure?" }
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:start_date, :end_date, :status)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<%# Banner and title for the page %>
<main class="bg-blue-200 w-full bg-opacity-25">
  <div class="w-full h-80 bg-cover bg-no-repeat bg-center bg-[url('https://images.unsplash.com/photo-1616549972169-0a0d961c9905?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80')] bg-black bg-opacity-25">
    <div class="w-full h-full">
      <div class="flex h-full justify-center items-center">
        <%# Wanted to add text shadow to title but not supported by Tailwind.  Maybe maunally enter it? %>
        <p class="text-4xl font-bold text-blue-100 mb-6 font-serif">Transaction History</p>
      </div>
    </div>
  </div>

  <%# Bar with the links for filtering the search %>
  <div class="w-full h-20 bg-blue-100">
    <form action="transactions" method="get">
      <div class="flex justify-evenly items-center h-20">
        <div class="font-serif font-bold text-slate-600">
          <label for="role">Transaction Role:</label>
          <select name="role" id="role" class="rounded">
            <option value="all">All</option>
            <option value="user">As User</option>
            <option value="owner">As Owner</option>
          </select>
        </div>
        <div class="font-serif font-bold text-slate-600">
          <label for="status">Transaction Status:</label>
          <select name="status" id="status" class="rounded">
            <option value="all">All</option>
            <option value="scheduled">Scheduled</option>
            <option value="in-progress">In Progress</option>
            <option value="completed">Completed</option>
          </select>
        </div>
        <div class="font-serif font-bold text-slate-800">
          <input type="submit" value="Filter Transactions" class="p-3 rounded-md bg-blue-300 hover:bg-blue-200">
        </div>
      </div>

    </form>
  </div>

  <%# Container for all transaction cards %>
  <div class="w-full px-20 py-10 mb-10 flex flex-col items-center" >
    <% if @transactions.count > 0 %>
      <% @transactions.each do |transaction| %>
        <%#  Div for each card%>
        <div class="w-full font-serif text-slate-600 flex h-52 border my-5 rounded-lg shadow hover:shadow-xl hover:shadow-indigo-100 shadow-sky-100 bg-white">
          <%# Card image %>
          <% if transaction.car.photos.count > 0 %>
            <div class="w-1/4 bg-center bg-cover rounded-l-lg" style="background-image: url('<%= cl_image_path transaction.car.photos[0].key, height: 300, width: 400, crop: :fill %>')">
            </div>
          <% else %>
            <div class="w-1/4 bg-center bg-cover rounded-l-lg bg-[url('<%= transaction.car.image_url %>')]">
            </div>
          <% end %>
          <%# Card information %>
          <div class="w=3/4 flex flex-col grow justify-between px-2 py-1">
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">Status: <%= transaction.status %></p>
              </div>
              <div class="w-1/2">
                <p class="">Confirmation Number:</p>
              </div>
            </div>
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">User: <%= transaction.user.name %></p>
              </div>
              <div class="w-1/2">
                <p class="">Car Owner: <%= transaction.car.owner.name %></p>
              </div>
            </div>
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">Pick-up Date: <%= transaction.start_date%></p>
              </div>
              <div class="w-1/2">
                <p class="">Pick-up Location: <%= transaction.car.location%></p>
              </div>
            </div>
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">Drop-off Date: <%= transaction.end_date%></p>
              </div>
              <div class="w-1/2">
                <p class="">Total Days: <%= (transaction.end_date - transaction.start_date).to_i %></p>
              </div>
            </div>
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">Total Price: $<%= (transaction.end_date - transaction.start_date).to_i * transaction.car.price %></p>
              </div>
              <div class="w-1/2 flex">
                <%= link_to new_transaction_review_path(transaction) do %>
                  <p class="bg-blue-200 py-1 px-3 rounded">Leave Review</p>
                <% end %>
                <div class="grow-1"></div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center text-32">No transactions</p>
    <% end %>


    <% if @owned_transactions.count > 0 %>
      <% @owned_transactions.each do |transaction| %>
        <%#  Div for each card%>
        <div class="w-full font-serif text-slate-600 flex h-48 border my-5 rounded-lg shadow hover:shadow-xl hover:shadow-indigo-100 shadow-sky-100 bg-white">
          <%# Card image %>
          <% if transaction.car.photos.count > 0 %>
            <div class="w-1/4 bg-center bg-cover rounded-l-lg" style="background-image: url('<%= cl_image_path transaction.car.photos[0].key, height: 300, width: 400, crop: :fill %>')">
            </div>
          <% else %>
            <div class="w-1/4 bg-center bg-cover rounded-l-lg bg-[url('https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80')]">
            </div>
          <% end %>
          <%# Card information %>
          <div class="w=3/4 flex flex-col grow justify-between px-2 py-1">
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">Status: <%= transaction.status %></p>
              </div>
              <div class="w-1/2">
                <p class="">Confirmation Number:</p>
              </div>
            </div>
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">User: <%= transaction.user.name %></p>
              </div>
              <div class="w-1/2">
                <p class="">Car Owner: <%= transaction.car.owner.name %></p>
              </div>
            </div>
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">Pick-up Date: <%= transaction.start_date%></p>
              </div>
              <div class="w-1/2">
                <p class="">Pick-up Location: <%= transaction.car.location%></p>
              </div>
            </div>
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">Drop-off Date: <%= transaction.end_date%></p>
              </div>
              <div class="w-1/2">
                <p class="">Total Days: <%= (transaction.end_date - transaction.start_date).to_i %></p>
              </div>
            </div>
            <%# Card row %>
            <div class="flex">
              <div class="w-1/2">
                <p class="">Total Price: $<%= (transaction.end_date - transaction.start_date).to_i * transaction.car.price %></p>
              </div>
              <div class="w-1/2">
                <p class=""></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center text-32">No transactions</p>
    <% end %>
  </div>
</main>

app/views/transactions/new.html.erb
<h1>test</h1>

app/views/transactions/show.html.erb
<h1>You are authorized to see</h1>