config/routes.rb
Rails.application.routes.draw do
  root to: "cars#landing"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cars
  # get 'user_session', to: 'users/sessions#show'
  resources :users, only: [:show]
  resources :transactions, only: [:index, :show, :create, :destroy] do
    resources :reviews
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <main>
      <nav class="flex items-center justify-between flex-wrap bg-gradient-to-r from-orange-300 via-blue-200 to-indigo-200 p-6">

          <div class="flex-shrink-0 text-white mr-6">
            <%= link_to root_path, class: "flex items-center" do %>
              <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
              <span class="font-semibold font-serif text-2xl tracking-tight">Carbnb</span>
            <% end %>
          </div>

        <%#
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
            <svg class="fi><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>ll-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"
          </button>
        </div>
        %>

        <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
          <div class="text-sm lg:flex-grow">
            <%= link_to cars_path do %>
              <p class="block mt-4 lg:inline-block text-xl lg:mt-0 text-slate-700 hover:text-white mr-4 ml-8 font-serif">
                Browse
              </p>
            <% end %>
            <% if current_user %>
              <%= link_to transactions_path do%>
                <p class="block mt-4 lg:inline-block lg:mt-0 text-xl text-slate-700 hover:text-white mr-4 ml-4 font-serif">
                  Transactions
                </p>
              <% end %>
            <% end %>
            <% if current_user %>
              <%= link_to user_path(current_user) do %>
                <p class="block mt-4 lg:inline-block lg:mt-0 text-xl text-slate-700 hover:text-white ml-4 font-serif">
                  My Profile
                </p>
              <% end %>
            <% end %>
          </div>
          <div>
            <% if current_user %>
              <%= button_to destroy_user_session_path, method: :delete, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" do %>
                LOG OUT
              <% end %>
            <% else %>
              <%= button_to new_user_session_path, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0" do %>
                LOG IN
              <% end %>
            <% end %>

          </div>
        </div>
      </nav>

      <%= yield %>
    </main>
  </body>
</html>